#!/bin/sh
cat > /dev/null
BASE=/usr/home/sites; export BASE; APP=blogalba; export APP
START_OPTS="--workers 1"; export START_OPTS
cd $BASE/$APP; git pull; cd -
cd $BASE/$APP.mirror.git; git pull; git push; cd -
#git --git-dir $BASE/$APP/.git --work-tree $BASE/$APP pull
[ ! -z "$(find $BASE/$APP -type d -name .git -prune -o -type f -mmin -1 -print|egrep '(p(ost|age)s/|lib$)')" ] || exit
echo "Restarting $APP"; $BASE/$APP/start