#!/bin/tcsh
#p5env setup
if ! $?PATH setenv PATH '';
if "${PATH}" != '' setenv PATH "/usr/home/sites/perl5/bin:${PATH}";
if "${PATH}" == '' setenv PATH "/usr/home/sites/perl5/bin";
if ! $?PERL5LIB setenv PERL5LIB '';
if "${PERL5LIB}" != '' setenv PERL5LIB "/usr/home/sites/perl5/lib/perl5:${PERL5LIB}";
if "${PERL5LIB}" == '' setenv PERL5LIB "/usr/home/sites/perl5/lib/perl5";
if ! $?PERL_LOCAL_LIB_ROOT setenv PERL_LOCAL_LIB_ROOT '';
if "${PERL_LOCAL_LIB_ROOT}" != '' setenv PERL_LOCAL_LIB_ROOT "/usr/home/sites/perl5:${PERL_LOCAL_LIB_ROOT}";
if "${PERL_LOCAL_LIB_ROOT}" == '' setenv PERL_LOCAL_LIB_ROOT "/usr/home/sites/perl5";
if ! $?PERL_MB_OPT setenv PERL_MB_OPT '';
setenv PERL_MB_OPT "--install_base "\""/usr/home/sites/perl5"\""";
if ! $?PERL_MM_OPT setenv PERL_MM_OPT '';
setenv PERL_MM_OPT "INSTALL_BASE=/usr/home/sites/perl5";

pkill -F /home/sites/blogalba.pid 2>/dev/null
setenv BLOGALBA_DIR "/home/sites/blogalba/"
plackup -s Starman -D -p 42069 /home/sites/blogalba/blogalba --pid /home/sites/blogalba.pid --workers 1
